project:
  output-dir: "_staff-site"
  
metadata-files:
  - "sidebar-nav.yml"

# Modify aesthetics and add Guide to navbar
website:
  title: "Stat 20 Staff Site"
  open-graph:
    site-name: "Stat 20 Staff Site"
  navbar:
    background: warning
    right:
      - text: "Staff Guide"
        href: staff-guide/index.qmd
      - text: "docs"
        href: docs/index.qmd
  # sidebar:
  #   - id: staff-guide
  #     title: "Staff Guide"
  #     style: floating
  #     align: left
  #     contents:
  #       - staff-guide/index.qmd
  #       - staff-guide/roles-and-expectations.qmd
  #       - staff-guide/grading.qmd
  #       - staff-guide/pre-semester-checklist.qmd
  #       
  #   - id: docs
  #     title: "Docs"
  #     style: floating
  #     align: left
  #     contents:
  #       - section: Documention
  #         href: docs/index.qmd
  #         contents:
  #           - docs/website.qmd
  #           - docs/assignments.qmd
  #           - docs/slides.qmd
        
        