<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Stat 20 - Summarizing Numerical Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-WP7F4QKDC8"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-WP7F4QKDC8', { 'anonymize_ip': true});
</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="Stat 20 - Summarizing Numerical Data">
<meta property="og:description" content="Seeing the forest for the trees.">
<meta property="og:image" content="https://stat20.berkeley.edu/summer-2024/2-summarizing-data/02-summarizing-numerical-data/images/violins-sm.png">
<meta property="og:site_name" content="Stat 20">
<meta property="og:image:height" content="376">
<meta property="og:image:width" content="612">
<meta name="twitter:title" content="Stat 20 - Summarizing Numerical Data">
<meta name="twitter:description" content="Seeing the forest for the trees.">
<meta name="twitter:image" content="https://stat20.berkeley.edu/summer-2024/2-summarizing-data/02-summarizing-numerical-data/images/violins-sm.png">
<meta name="twitter:image-height" content="376">
<meta name="twitter:image-width" content="612">
<meta name="twitter:card" content="summary_large_image">
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-sm " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/stat20-hex-small.png" alt="Stat 20 logo" class="navbar-logo"></a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../office-hours.html"> 
<span class="menu-text">Office Hours</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../notes.html"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../assignments.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools tools-wide">
    <a href="https://edstem.org/us/courses/51198" title="" class="quarto-navigation-tool px-1" aria-label="Ed Discussion Forum"><i class="bi bi-chat-fill"></i></a>
    <a href="https://www.gradescope.com/courses/693050" title="" class="quarto-navigation-tool px-1" aria-label="Gradescope"><i class="bi bi-bar-chart-fill"></i></a>
    <a href="https://stat20.datahub.berkeley.edu/" title="" class="quarto-navigation-tool px-1" aria-label="RStudio"><i class="bi bi-r-circle-fill"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#constructing-graphical-summaries" id="toc-constructing-graphical-summaries" class="nav-link active" data-scroll-target="#constructing-graphical-summaries">Constructing Graphical Summaries</a>
  <ul class="collapse">
<li><a href="#histograms" id="toc-histograms" class="nav-link" data-scroll-target="#histograms">Histograms</a></li>
  <li><a href="#density-plots" id="toc-density-plots" class="nav-link" data-scroll-target="#density-plots">Density plots</a></li>
  <li><a href="#violin-plots" id="toc-violin-plots" class="nav-link" data-scroll-target="#violin-plots">Violin plots</a></li>
  </ul>
</li>
  <li><a href="#describing-distributions" id="toc-describing-distributions" class="nav-link" data-scroll-target="#describing-distributions">Describing Distributions</a></li>
  <li>
<a href="#constructing-numerical-summaries" id="toc-constructing-numerical-summaries" class="nav-link" data-scroll-target="#constructing-numerical-summaries">Constructing Numerical Summaries</a>
  <ul class="collapse">
<li><a href="#measures-of-center" id="toc-measures-of-center" class="nav-link" data-scroll-target="#measures-of-center">Measures of Center</a></li>
  <li><a href="#measures-of-spread" id="toc-measures-of-spread" class="nav-link" data-scroll-target="#measures-of-spread">Measures of Spread</a></li>
  </ul>
</li>
  <li>
<a href="#the-ideas-in-code" id="toc-the-ideas-in-code" class="nav-link" data-scroll-target="#the-ideas-in-code">The Ideas in Code</a>
  <ul class="collapse">
<li><a href="#calculating-numerical-summaries" id="toc-calculating-numerical-summaries" class="nav-link" data-scroll-target="#calculating-numerical-summaries">Calculating Numerical Summaries</a></li>
  <li><a href="#groupwise-operations" id="toc-groupwise-operations" class="nav-link" data-scroll-target="#groupwise-operations">Groupwise Operations</a></li>
  <li><a href="#plotting-with-categorical-variables" id="toc-plotting-with-categorical-variables" class="nav-link" data-scroll-target="#plotting-with-categorical-variables">Plotting with Categorical Variables</a></li>
  </ul>
</li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="notes.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Summarizing Numerical Data</h1>
<p class="subtitle lead">Seeing the forest for the trees.</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><ul>
<li>Man feigns madness, contemplates life and death, and seeks revenge.</li>
<li>Son avenges his father, and it only takes four hours.</li>
<li>A tragedy written by the English playwright around 1600.</li>
<li>29,551 words on a page.</li>
</ul>
<p>You may recognize each of these as summaries of the play, “Hamlet”. None of these are wrong, per se, but they do focus on very different aspects of the work. Summarizing something as rich and complex as Hamlet invariably involves a large degree of omission; we’re reducing a document of 29,551 words down to a single sentence or phrase, after all. But summarization also involves important choices around what to include.</p>
<p>The same considerations of omission and inclusion come into play when developing a numerical or graphical summary of a data set. Some guidance to bear in mind:</p>
<p><em>What should I include?</em></p>
<ul>
<li>Qualities relevant to the question you’re answering or claim you’re making</li>
<li>Features that are aligned with the interest of your audience</li>
</ul>
<p><em>What should I omit?</em></p>
<ul>
<li>Qualities that are irrelevant, distracting, or deceptive</li>
<li>Replicated or assumed information</li>
</ul>
<p>In these notes we’ll keep this guidance in mind as we discuss how to summarize numerical data with graphics, in words, and with statistics. Specifically, we will learn how to:</p>
<ul>
<li>Summarize one numerical variable</li>
<li>Summarize one numerical variable broken up into levels of a second, categorical variable.</li>
</ul>
<p>Summarizing <em>two</em> numerical variables is a task which deserves its own set of notes; that set of notes will come later on!</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code along
</div>
</div>
<div class="callout-body-container callout-body">
<p>As you read through these notes, you’ll find figures and tables that were produced by running R code. Specifically, you will see visualizations constructed with <code>ggplot2</code>, and tables created with another package in the <code>tidyverse</code> library, <strong><code>dplyr</code></strong>.</p>
<p>The <code>ggplot2</code> code for the visualizations will be presented below. We will introduce <code>dplyr</code> in the <strong>Ideas in Code</strong> section.</p>
<p>Feel free to open up RStudio and code along with us, making sure that you load the <code>stat20data</code> library and <code>penguins</code> dataset as we did last time!</p>
</div>
</div>
<section id="constructing-graphical-summaries" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="constructing-graphical-summaries">Constructing Graphical Summaries</h2>
<p>Let’s turn to an example admittedly less complex than Hamlet: the Palmer penguins. One of the numerical variables Dr.&nbsp;Gorman recorded was the length of the bill in millimeters. The values of the first 16 penguins are:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="images/culmen-depth.png" class="img-fluid" alt="A sketch of the a penguin in profile, with a measuring bar indicating a measurement of the bill length." width="250"></p>
</div></div><div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bill_16</span> <span class="op">&lt;-</span> <span class="va">penguins</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">bill_length_mm</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">slice</span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">16</span><span class="op">)</span></span>
<span><span class="va">bill_16</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 1
   bill_length_mm
            &lt;dbl&gt;
 1           39.1
 2           39.5
 3           40.3
 4           36.7
 5           39.3
 6           38.9
 7           39.2
 8           41.1
 9           38.6
10           34.6
11           36.6
12           38.7
13           42.5
14           34.4
15           46  
16           37.8</code></pre>
</div>
</div>
<p>We have many options for different plot types that we could use to summarize this data graphically. To understand the differences, it’s helpful to lay out the criterion that we hold for a summary to be a success. Let’s call those criteria the <em>desiderata</em>, a word meaning “that which is desired or needed”.</p>
<p>For our first graphic, let’s set a high bar.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Desiderata
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>All information must be preserved.</li>
</ul>
</div>
</div>
<p>The most commonly used graphic that fulfills this criterion is the <strong>dot plot</strong>.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, </span>
<span>       mapping <span class="op">=</span> <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">bill_length_mm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_dotplot</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>The dot plot is, in effect, a one-dimensional scatter plot. Each observation shows up as a dot and its value corresponds to its location along the x-axis. Importantly, it fulfills our desiderata: given this graphic, one can recreate the original data perfectly. There was no information loss.</p>
<p>As the number of observations grow, however, this sort of graphical summary becomes unwieldy. Instead of focusing on the value of each observation, it becomes more practical to focus on the general shape of the distribution. Let’s consider a broader goal for our graphic.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Desiderata
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Balance depiction of the general characteristics of the distribution with a fidelity to the individual observations.</li>
</ul>
</div>
</div>
<p>There are several types of graphics that meet this criterion: the histogram, the density plot, and the violin plot.</p>
<section id="histograms" class="level3"><h3 class="anchored" data-anchor-id="histograms">Histograms</h3>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, </span>
<span>       mapping <span class="op">=</span> <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">bill_length_mm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>At first glance, a histogram looks like deceptively like a bar chart. There are bars arranged along the x-axis according to their values with heights that correspond to the count of each value found in the data set. So how is this not a bar chart?</p>
<p>A histogram involves <em>aggregation</em>. The first step in creating a histogram is to divide the range of the variable into bins of equal size. The second step is to count up the number of observations that occur in each bin. In this way, some observations will have their own bar (every bar with a count of one) but other observations will be aggregated into the same bar: the tallest bar, with a count of 3, corresponds to all observations from 39.09 to 39.30: 39.1, 39.2, and 39.3.</p>
<p>The degree of aggregation performed by the histogram is determined by the <em>binwidth</em>. Most software will automatically select the binwidth<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, but it can be useful to tinker with different values to see the distribution at different levels of aggregation. The <code>binwidth</code> argument within <code>geom_histogram()</code> can be altered to implement this. Here are four histograms of the same data that use four different binwidths (try setting your histogram’s binwidth to one of the options in the below plots)!</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>If you are interested in only the coarsest structure in the distribution, best to use the larger binwidths. If you want to see more detailed structure, a smaller binwidth is better.</p>
<p>There is a saying that warns about times when you, “can’t see the forest for the trees”, being overwhelmed by small details (the trees) and unable to see the bigger picture (the forest). The histogram, as a graphical tool for summarizing the distribution of a numerical variable, offers a way out. Through your choice of binwidth, you can determine how much to focus on the forest (large bindwidth) or the trees (small binwidth).</p>
</section><section id="density-plots" class="level3"><h3 class="anchored" data-anchor-id="density-plots">Density plots</h3>
<p>Imagine that you build a histogram and place a cooked piece of spaghetti over the top of it. The curve created by the pasta is a form of a density plot.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, </span>
<span>       mapping <span class="op">=</span> <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">bill_length_mm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_density</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Besides the shift from bars to a smooth line, the density plot also changes the y-axis to feature a quantity called “density”. We will return to define this term later in the course, but it’s sufficient to know that the values on the y-axis of a density plot are rarely useful. The important information is relative: an area of the curve with twice the density as another area has roughly twice the number of observations.</p>
<p>The density plot, like the histogram, offers the ability to balance fidelity to the individual observations against a more general shape of the distribution. You can tip the balance to feature what you find most interesting but adjusting the <em>bandwidth</em> of the density plot. This can be done by including the <code>bw</code> argument inside of density and setting it to a number (again, try setting it to one of the options in the below plots)!</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>A density curve tends to convey the overall shape of a distribution more quickly than does a histogram, but be sure to experiment with different bandwidths. Strange but important features of a distribution can be hidden behind a density curve that is too smooth.</p>
</section><section id="violin-plots" class="level3"><h3 class="anchored" data-anchor-id="violin-plots">Violin plots</h3>
<p>Often we’re interested not in the distribution of a single variable, but in the way the distribution of that variable changes from one group of observational units to another. Let’s add this item to our list of criteria for a statistical graphic.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Desiderata
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Balance depiction of the general characteristics of the distribution with a fidelity to the individual observations.</li>
<li>Allow for easy comparisons between groups.</li>
</ul>
</div>
</div>
<p>There are several different ways to compare the distribution of a variable across two or more groups, but one of the most useful is the violin plot. Here is a violin plot of the distribution of bill length across the three species of penguins.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, </span>
<span>       mapping <span class="op">=</span> <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">bill_length_mm</span>,</span>
<span>                     y <span class="op">=</span> <span class="va">species</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_violin</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of bill length in each species is represented by a shape that often looks like a violin but is in fact a simple density curve reflected about its x-axis. This means that you can tinker with a violin plot the same as a density plot, but changing the bandwidth.</p>
<p>If this plot type looks familiar, you may have seen its cousin, the box plot.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, </span>
<span>       mapping <span class="op">=</span> <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span> <span class="va">bill_length_mm</span>,</span>
<span>                     y <span class="op">=</span> <span class="va">species</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>The box plot conveys a similar story to the violin plot: Adelies have shorter bills than Chinstraps and Gentoos. Box plots have the advantage of requiring very little computation to construct<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, but in a world of powerful computers, that is no longer remarkable. What they lack is a “smootness-knob” that you can turn to perform more or less smoothing. For this reason, violin plots are a more flexible alternative to box plots.</p>
</section></section><section id="describing-distributions" class="level2"><h2 class="anchored" data-anchor-id="describing-distributions">Describing Distributions</h2>
<p>The desideratum that we used to construct the histogram and the violin plot include the ability to “depict general characteristics of the distribution”. The most important characteristics of a distribution are its <em>shape</em>, <em>center</em>, and <em>spread</em>.</p>
<p>When describing the shape of a distribution in words, pay attention to its <em>modality</em> and <em>skew</em>. The modality of a distribution captures the number of distinct peaks (or modes) that are present.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/modality.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="500"></p>
</figure>
</div>
<p>A good example of a distribution that would be described as unimodal is the original density plot of bill lengths of 16 Adelie penguins (below left). There is one distinct peak around 39. Although there is another peak around 34, it is not prominent enough to be considered a distinct mode. The distribution of the bill lengths of all 344 penguins (below right), however, can be described as bimodal.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Multiple modes are often a hint that there is something more going on. In the plot to the right above, Chinstraps and Gentoo penguins, which are larger, are clumped under the right mode while the smaller Adelie penguins are dominant in the left mode.</p>
<p>The other important characteristic of the shape of a distribution is its skew.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/skew.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="500"></p>
</figure>
</div>
<p>The skew of a distribution describes the behavior of its tails: whether the right tail stretches out (right skew), the left tail stretches out (left skew), or if both tails are of similar length (symmetric). An example of a persistently right skewed distribution is household income in the United States:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/income-dist.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="400"></p>
</figure>
</div>
<p>In the US, the richest households have much much higher incomes than most, while the poorest households have incomes that are only a bit lower than most.</p>
<p>When translating a graphical summary of a distribution into words, some degree of judgement must be used. When is a second peak a mode and when is it just a bump in the distribution? When is one of the tails of a distribution long enough to tip the description from being symmetric to being right skewed? You’ll hone your judgement in part through repeated practice: looking at lots of distributions and readings lots of descriptions. You can also let the questions of inclusion and omission be your guide. Is the feature a characteristic relevant to the question you’re answering and the phenomenon you’re studying? Or is it just a distraction from the bigger picture?</p>
<p>Modality and skew capture the shape of the distribution, but how do we describe its center and spread? “Eyeballing it” by looking at a graphic is an option. A more precise option, though, is to calculate a statistic.</p>
</section><section id="constructing-numerical-summaries" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="constructing-numerical-summaries">Constructing Numerical Summaries</h2>
<p>Statistics is both an area of academic study and the object of that study. Any numerical summary of a data set - a mean or median, a count or proportion - is a <em>statistic</em>. A statistic is, fundamentally, a mathematical function where the data is the input and the output is the observed statistic.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="images/function-machine.png" class="img-fluid" width="250"></p>
</div></div><p>Statisticians don’t just study statistics, though, they <em>construct</em> them. A statistician gets to decide the form of <span class="math inline">\(f\)</span> and, as with graphics, they construct it to fulfill particular needs: the desiderata.</p>
<p>To examine the properties of common statistics, let’s move to an even simpler data set: a vector called <code>x</code> that holds 11 integers.</p>
<p><span class="math display">\[8, 11, 7, 7, 8, 11,  9,  6,  10,  7,  9\]</span></p>
<!-- In these notes we'll walk through statistics - numerical and graphical - that you'll be familiar with.  -->
<!-- The primary building material that statisticians use to build understanding is data. In order to extract meaning from the raw data, we construct statistics and statistical graphics, and they're designed to have particular properties. -->
<section id="measures-of-center" class="level3 page-columns page-full"><h3 class="anchored" data-anchor-id="measures-of-center">Measures of Center</h3>
<p>The mean, the median, and the mode are the three standard statistics used to measure the center of a distribution. Despite their ubiquity, these three are not carved somewhere on a stone tablet. They’re common because they’re useful and they’re useful because they were constructed very thoughtfully.</p>
<p>Let’s start by laying out some possible criteria for a measure of center.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Desiderata
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Synthesizes the magnitudes of all <span class="math inline">\(n\)</span> observations.</li>
<li>As close as possible to all of the observations.</li>
</ul>
</div>
</div>
<p>The (arithmetic) <strong>mean</strong> fulfills all of these needs.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The function in R: <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code></p>
</div></div><p><span class="math display">\[
\frac{8 + 11 + 7 + 7 + 8 + 11 + 9 + 6 + 10 + 7 + 9}{11} = \frac{93}{11} = 8.45
\]</span></p>
<p>The mean synthesizes the magnitudes by taking their sum, then keeps that sum from getting larger than any of the observations by dividing by <span class="math inline">\(n\)</span>. In order to express this function more generally, we use the following notation</p>
<p><span class="math display">\[
\bar{x} = \frac{x_1 + x_2 + \ldots + x_n}{n}
\]</span></p>
<p>where <span class="math inline">\(x_1\)</span> is the first observation, <span class="math inline">\(x_2\)</span> is the second observation, and so on till the <span class="math inline">\(n^{th}\)</span> observation, <span class="math inline">\(x_n\)</span>; and <span class="math inline">\(\bar{x}\)</span> is said “x bar”.</p>
<p>The mean is the most commonly used measure of center, but has one notable drawback. What if one of our observations is an <em>outlier</em>, that is, has a value far more extreme than the rest of the data? Let’s change the <span class="math inline">\(6\)</span> to <span class="math inline">\(-200\)</span> and see what happens.</p>
<p><span class="math display">\[
\frac{8 + 11 + 7 + 7 + 8 + 11 + 9 - 200 + 10 + 7 + 9}{11} = \frac{-113}{11} = -10.27
\]</span></p>
<p>The mean has plummeted to -10.27, dragged down by this very low outlier. While it is doing it’s best to stay “as close as possible to all of the observations”, it isn’t doing a very good job of representing 10 of the 11 values.</p>
<p>With this in mind, let’s alter the first criterion to inspire a different statistic.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Desiderata
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Synthesize the <em>order</em> of all <span class="math inline">\(n\)</span> observations.</li>
<li>As close as possible to all of the observations.</li>
</ul>
</div>
</div>
<p>If we put the numbers in order from smallest to largest, then the number that is as close as possible to all observations will be the middle number, the <strong>median</strong>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The function in R: <code><a href="https://rdrr.io/r/stats/median.html">median()</a></code></p>
</div></div><p><span class="math display">\[ 6 \quad 7 \quad 7 \quad  7 \quad 8 \quad {\Large 8} \quad 9 \quad 9 \quad 10 \quad 11  \quad 11\]</span></p>
<p>As measured by the median, the center of this distribution is 8 (recall the mean measured 8.45). If there were an even number of observations, the convention is to take the mean of the middle two values.</p>
<p>The median has the desirable property of being resistant (or “robust”) to the presence of outliers. See how it responds to the inclusion of -200.</p>
<p><span class="math display">\[ -200 \quad 7 \quad 7 \quad  7 \quad 8 \quad {\Large 8} \quad 9 \quad 9 \quad 10 \quad 11  \quad 11\]</span></p>
<p>With this outlier, the median remains at 8 while the mean had dropped to -10.27. This property makes the median the favored statistic for capturing the center of a skewed distribution.</p>
<p>What if we took a stricter notion of “closeness”?</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Desiderata
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Is identical to as many observations as possible.</li>
</ul>
</div>
</div>
<p>That leads us to the measure of the <strong>mode</strong>, or the most common observation. For our example data set, the mode is <span class="math inline">\(7\)</span>.</p>
<p><span class="math display">\[ 6 \quad {\Large 7 \quad 7 \quad  7} \quad 8 \quad 8 \quad 9 \quad 9 \quad 10 \quad 11  \quad 11\]</span></p>
<p>While using the mode for this data set is sensible, it is common in numerical data for each value to be unique<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. In that case, there are no repeated values, and no identifiable mode. For that reason, it is unusual to calculate the mode to describe the center of a numerical variable.</p>
<p>For categorical data, however, the mode is very useful. The mode of the species variable among the Palmer penguins is “Adelie”. Trying to compute the mean or the median species will leave you empty-handed. This is one of the lingering lessons of the Taxonomy of Data: the type of variable guides how it is analyzed.</p>
</section><section id="measures-of-spread" class="level3 page-columns page-full"><h3 class="anchored" data-anchor-id="measures-of-spread">Measures of Spread</h3>
<p>There are many different ways to capture spread or dispersion of data. Here are some basic desiderata we might hope to achieve with a measure of spread.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Desiderata
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The statistic should be low when the numbers are the same or very similar to one another.</li>
<li>The statistic should be high when the numbers are very different.</li>
<li>The statistic should not grow or shrink with the sample size ( n ).</li>
</ul>
</div>
</div>
<p>These desiderata are not met by every measure of spread. Here is one such measure of spread which does not meet all three!</p>
<section id="range" class="level4"><h4 class="anchored" data-anchor-id="range">Range</h4>
<p>The range of a set of numbers is simply the maximum number in the dataset minus its minimum.</p>
<p><span class="math display">\[ range = max - min\]</span></p>
<p>For our set of numbers, the range will be <span class="math inline">\(5\)</span>.</p>
<p><span class="math display">\[ {\Large 6} \quad {\ 7 \quad 7 \quad  7} \quad 8 \quad 8 \quad 9 \quad 9 \quad 10 \quad 11  \quad {\Large 11}\]</span></p>
<p>Although the first two criterion above are met by the range, the third one is not. The reason is that if we add a number to our set which is greater than the maximum value, or smaller than the minimum value, the value of range will change. Therefore, increasing our sample size <span class="math inline">\(n\)</span> could cause our statistic to grow or shrink.</p>
<p>Here are some measures of spread which <em>do</em> meet all three criterion. They do this by using incorporating some of the measures of center that we have already talked about, such as the mean and the median.</p>
</section><section id="the-sample-variance" class="level4 page-columns page-full"><h4 class="anchored" data-anchor-id="the-sample-variance">The Sample Variance</h4>
<p>The sample variance:</p>
<ul>
<li>Takes the differences from each observation, <span class="math inline">\(x_i\)</span>, to the sample mean <span class="math inline">\(\bar{x}\)</span>;</li>
<li>squares them;</li>
<li>adds them all up;</li>
<li>divides by <span class="math inline">\(n - 1\)</span>;</li>
<li>then finally, takes the square root.</li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p>The function in R: <code><a href="https://rdrr.io/r/stats/cor.html">var()</a></code></p>
</div></div><p><span class="math display">\[ s^2 = \frac{1}{n - 1} \sum_{i=1}^{n} \left( x_i - \bar{x}\right)^2 \]</span> This formula is rather dense; don’t worry! We won’t ask you to memorize it. The key is that is fits the three criterion we were hoping for.</p>
<p>The distance <span class="math inline">\((x_i - \bar{x})^2\)</span> will be small when <span class="math inline">\(x_i\)</span> is close to the mean, and large when it’s not. This means the first two criterion are met. Additionally, because we are dividing by a number close to <span class="math inline">\(n\)</span>, (<span class="math inline">\(n-1\)</span>), the statistic does not grow or shrink with <span class="math inline">\(n\)</span>. This means the last criterion is met!</p>
<p>One other question you might have: why the square?</p>
<p>The reason is that spread/distance is a positive quantity. Recall that the mean of our list was <span class="math inline">\(8.45\)</span>. Two numbers in our list, <span class="math inline">\(7\)</span> and <span class="math inline">\(9\)</span>, are both <span class="math inline">\(1.45\)</span> units away from the mean. However, <span class="math inline">\(7-8.45 = -1.45\)</span> and <span class="math inline">\(9-8.45 = 1.45\)</span>. As part of the sum, we will have to add up <span class="math inline">\(-1.45\)</span> and <span class="math inline">\(1.45\)</span>, which comes out to <span class="math inline">\(0\)</span>.</p>
<p>This means that the information from the two data points <span class="math inline">\(7\)</span> and <span class="math inline">\(9\)</span> have been canceled out! We don’t want this to happen, so we need to make all of the terms in the sum positive. The square takes care of that.</p>
<p>For our list:</p>
<p><span class="math display">\[ s^2 =  2.87 \]</span></p>
</section><section id="the-sample-standard-deviation" class="level4 page-columns page-full"><h4 class="anchored" data-anchor-id="the-sample-standard-deviation">The Sample Standard Deviation</h4>
<p><span class="math display">\[ s = \sqrt{\frac{1}{n - 1} \sum_{i=1}^{n} \left( x_i - \bar{x}\right)^2} \]</span></p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The function in R: <code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code></p>
</div></div><p>The sample standard deviation <span class="math inline">\(s\)</span> is the same as the sample variance <span class="math inline">\(s^2\)</span>: we’ve just taken the square root. One reason for using the sample standard deviation is that it at times is more interpret-able than the sample variance, since it’s measured in units rather than units squared.</p>
<p>For our list:</p>
<p><span class="math display">\[ s =  1.69 \]</span> We can say, therefore, that each data point is about 1.7 units apart from each other.</p>
<hr>
<p>While the sample variance and sample standard deviation are great for measuring symmetric data (which appear enough in statistics) and also show up a lot in the theory of some topics that we will later discover, they do have their faults.</p>
<p>Namely, when data is not symmetric, the square around <span class="math inline">\(x_i - \bar{x}\)</span> can cause some issues. Asymmetrical data will have many values <span class="math inline">\(x_i\)</span> (large or small) which are far from the mean <span class="math inline">\(\bar{x}\)</span>.</p>
<p>If <span class="math inline">\(x_i - \bar{x}\)</span> is large, then <span class="math inline">\((x_i - \bar{x})^2\)</span> will be <em>very</em> large. Therefore, <span class="math inline">\(s^2\)</span> and <span class="math inline">\(s\)</span> can produce values that are overestimates of the spread of <em>most</em> of the data. Here are two measures of spread which counter-act this.</p>
</section><section id="iqr-interquartile-range" class="level4 page-columns page-full"><h4 class="anchored" data-anchor-id="iqr-interquartile-range">IQR (Interquartile Range)</h4>
<p>The IQR is the difference between the median of the larger half of the sorted data set, <span class="math inline">\(Q3\)</span>, and the median of the smaller half, <span class="math inline">\(Q1\)</span>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The function in R: <code><a href="https://rdrr.io/r/stats/IQR.html">IQR()</a></code></p>
</div></div><p>&nbsp;</p>
<p><span class="math display">\[ IQR = Q_3 - Q_1 \]</span> &nbsp;</p>
<p>Let’s calculate the IQR for the list of eleven numbers we’ve been working with. First, we find the median of our dataset. That’s <span class="math inline">\(8\)</span>. Then, we split the data into two halves of five. Then we find the medians of these halves. and take the difference. These steps are visualized below.</p>
<p>&nbsp;</p>
<p><span class="math display">\[ 6 \quad 7 \quad {\Large 7 \quad  7} \quad 8 \quad  {\large 8} \quad 9 \quad {\Large 9 \quad 10} \quad 11  \quad 11\]</span> &nbsp;</p>
<p>We have that <span class="math inline">\(Q_3 = 9.5\)</span> and <span class="math inline">\(Q_1 = 7\)</span>. Then:</p>
<p>&nbsp;</p>
<p><span class="math display">\[IQR =  9.5−7 = 2.5\]</span></p>
<p>The reason the IQR works well for asymmetric data is because the measure of center it’s based on is the <em>median</em>, not the <em>mean</em>. The median, being just the middle point of the data and not a value obtained by calculation of all the numbers in a list, is not impacted when extreme values are tacked onto the end of the list.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Additional Desiderata
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Is robust to extreme values (outliers).</li>
</ul>
</div>
</div>
<p>Our final measure of spread is another option which is resillent against outliers, but is based off of the mean instead of the median.</p>
</section><section id="mean-absolute-deviation-mad" class="level4"><h4 class="anchored" data-anchor-id="mean-absolute-deviation-mad">Mean Absolute Deviation (MAD)</h4>
<p>The <span class="math inline">\(MAD\)</span> is very similar to the sample variance <span class="math inline">\(s^2\)</span>, except that:</p>
<ul>
<li>we divide by <span class="math inline">\(n\)</span> rather than <span class="math inline">\(n-1\)</span>;</li>
<li>we take the absolute value of <span class="math inline">\(x_i - \bar{x}\)</span> instead of squaring it.</li>
</ul>
<p><span class="math display">\[
MAD: \quad \frac{1}{n}\sum_{i = 1}^n |x_i - \bar{x}|
\]</span></p>
<p>The key difference is the second one. The MAD is great for summarizing skewed distributions because it isn’t bothered too much by the presence of extreme values in a set of numbers. That’s because the absolute value bar just ensures a number is positive; it doesn’t further amplify that number by squaring it.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Additional Desiderata
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Is robust to extreme values (outliers).</li>
</ul>
</div>
</div>
</section></section></section><section id="the-ideas-in-code" class="level2"><h2 class="anchored" data-anchor-id="the-ideas-in-code">The Ideas in Code</h2>
<p>Once you have your data in front of you, you’ve seen how we can form visual summaries with <code>ggplot2</code>. But how can we calculate numerical summaries? Furthermore, what if we are concerned about summarizing a portion of our data, like just one species of penguin at a time? We will answer these questions below, and introduce some new functions from the <code>dplyr</code> package (within the <code>tidyverse</code> library) along the way. We’ll also look at how <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code> can come in handy while plotting.</p>
<section id="calculating-numerical-summaries" class="level3"><h3 class="anchored" data-anchor-id="calculating-numerical-summaries">Calculating Numerical Summaries</h3>
<p>One example of a numerical variable we could have examine is the body mass of a particular penguin (measured in grams). Let’s calculate both a measure of center and spread for this variable.</p>
<p>To get an idea of what summaries we should pick, let’s revisit the density plot from earlier.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What we can glean from this figure is that the distribution of body masses across <em>all species of penguin</em> is skewed right. This means that, for instance, a more typical observation lies closer to 4000 grams than 5000 grams.</p>
<p>If we take an average, it is likely to be pulled to the right by the larger, but less typical, observations. The median observation, however, would be more resistant to this pull. Therefore, the median might be a nice choice for a measure of center. Similarly, since the IQR is initially constructed from the median, it will serve well here as a measure of spread.</p>
<p>Now, let’s calculate these values. We should first isolate our variable of interest. We can do this in code by using the <code>dplyr</code> function <strong><code>select()</code></strong>.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">body_mass</span> <span class="op">&lt;-</span> <span class="fu">select</span><span class="op">(</span><span class="va">penguins</span>, <span class="va">body_mass_g</span><span class="op">)</span></span>
<span><span class="va">body_mass</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 333 × 1
   body_mass_g
         &lt;int&gt;
 1        3750
 2        3800
 3        3250
 4        3450
 5        3650
 6        3625
 7        4675
 8        3200
 9        3800
10        4400
# ℹ 323 more rows</code></pre>
</div>
</div>
<p>As is custom with <code>dplyr</code> functions, the first argument goes to the data frame you are working with. The following arguments are more function specific. In <code>select()</code>’s case, we tell the computer which column/variable we are interested in.</p>
<p>Now, we can calculate our summaries. When working with a vector, we could use functions like <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> and <code><a href="https://rdrr.io/r/stats/median.html">median()</a></code> directly, e.g.&nbsp;<code>median(body_mass_g)</code>. However, <code>body_mass_g</code> is not a standalone vector but is now a column in a data frame called <code>body_mass</code>! Therefore, we need to access it through a <code>dplyr</code> function called <strong><code>summarise()</code></strong>.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">summarise</span><span class="op">(</span><span class="va">body_mass</span>, </span>
<span>          body_mass_median <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">body_mass_g</span><span class="op">)</span>,</span>
<span>          body_mass_IQR <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/IQR.html">IQR</a></span><span class="op">(</span><span class="va">body_mass_g</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  body_mass_median body_mass_IQR
             &lt;int&gt;         &lt;dbl&gt;
1             4050          1225</code></pre>
</div>
</div>
<p>Note that while the first argument goes to the name of the data frame, the following arguments are given to the names of the new columns that <code>summarise()</code> puts in another <em>new data frame</em> (one row by two columns). You can name the columns whatever you would like.</p>
<p>Based on what we’ve found, the median here supports the claim we made above: that a typical penguin has a body mass closer to 4000 grams than to 5000 grams. The middle 50 percent of the penguins have body masses within 1225/2 grams, or roughly 600 grams, of 4050.</p>
</section><section id="groupwise-operations" class="level3"><h3 class="anchored" data-anchor-id="groupwise-operations">Groupwise Operations</h3>
<p>Let’s return to the bill length examine of a particular penguin, measured in millimeters. Here is the density plot for <em>all of the data</em>; for simplicity, earlier we showed you the plot for only the first 16 observations.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot is interesting. It appears we have a bimodal shape! While it’s tempting to state that the data is roughly symmetric and calculate an overall mean, we should first see if there are any other variables at play. It stands to reason that different species of penguin might have different anatomical features. Let’s add species to the mix by using the <code>color</code> aesthetic (see if you can code along)!</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Aha! We now see that each penguin species has its own shape of distribution when it comes to bill length.</p>
<p>The example above demonstrates a very common scenario: you want to perform some calculations on one particular group of observations in your data set. But what if you want to do that same calculation for every group? For example, what if we’d like to find the average and standard deviation of bill length among each species of penguin <em>separately</em>?</p>
<p>This task - performing an operation on all groups of a data set one-by-one - is such a common data science task that nearly every software tool has a good solution. In the <code>dplyr</code> package, the solution is the <strong><code>group_by()</code></strong> function. Let’s see it in action.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">grouped_penguins</span> <span class="op">&lt;-</span> <span class="fu">group_by</span><span class="op">(</span><span class="va">penguins</span>, <span class="va">species</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Like most <code>tidyverse</code> functions, the first argument to <code>group_by()</code> is a data frame. The second argument is the name of the variable that you want to use to delineate groups. In this case, we want to group by species to calculate three separate mean/standard deviation pairs.</p>
<p>Now, assuming we roll with our new <code>grouped_penguins</code> data frame, we can use <code>summarise()</code> like we did before!</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">summarise</span><span class="op">(</span><span class="va">grouped_penguins</span>, </span>
<span>          bill_length_mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">bill_length_mm</span><span class="op">)</span>,</span>
<span>          bill_length_sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">bill_length_mm</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  species   bill_length_mean bill_length_sd
  &lt;fct&gt;                &lt;dbl&gt;          &lt;dbl&gt;
1 Adelie                38.8           2.66
2 Chinstrap             48.8           3.34
3 Gentoo                47.6           3.11</code></pre>
</div>
</div>
<p>From both the visuals and the numbers, we can see that Adelie penguins have much smaller bill lengths on average when compared to Chinstrap and Gentoo penguins. We also see that the Adelie distribution of bill lengths is less variable than the distributions of the other two species.</p>
</section><section id="plotting-with-categorical-variables" class="level3"><h3 class="anchored" data-anchor-id="plotting-with-categorical-variables">Plotting with Categorical Variables</h3>
<p>Finally, let’s return to the violin plot of bill lengths grouped by species of penguin.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What if I wanted the Adelie violin to show up on the top of the graph? By default, the violin plot puts the level first in the alphabetical order on the bottom of the plot. Therefore, I need to <em>reorder</em> the levels of species to put Adelie at the top. This is where <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code> will do the job!</p>
<p>As before, <code>bill_length_mm</code> is not a standalone vector but a column in a data frame! We cannot access it directly, e.g.&nbsp;by <code>factor(species, levels = c("Gentoo", "Chinstrap", "Adelie"))</code>.</p>
<p>Therefore, we use the <code>dplyr</code> function <strong><code>mutate()</code></strong>. A <strong>mutation</strong> involves changing the properties of an existing column, or adding a new one altogether (which we will explore next week).</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">reordered_penguins</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="va">penguins</span>, </span>
<span>  species <span class="op">=</span> </span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">species</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Gentoo"</span>, <span class="st">"Chinstrap"</span>, <span class="st">"Adelie"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The first argument of <code>mutate()</code> is dedicated to our data frame, <code>penguins</code>. The second argument can be the name of an existing column or the name of a new column (next week). We want to change <code>species</code> to be an altered version of itself, hence we name the second argument <code>species</code>. Make sure you understand where each set of parentheses closes and ends.</p>
<p>Now, assuming we roll with our new <code>reordered_penguins</code> data frame, we can use <code>ggplot()</code> like we did before!</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="summary" class="level2"><h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>A summary of a summaries…this better be brief! Summaries of numerical data - graphical and numerical - often involve choices of what information to include and what information to omit. These choices involve a degree of judgement and knowledge of the criteria that were used to construct the commonly used statistics and graphics.</p>


</section><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1"><p>The <code>ggplot2</code> package in R defaults to 30 bins across the range of the data. That’s a very rough rule-of-thumb, so tinkering is always a good idea.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>To read more about one common way to construct a box plot, see the <a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html#summary-statistics"><code>ggplot2</code> documentation</a>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>That is, unless you aggregate! The aggregation performed by a histogram or a density plot is what allows us to describe numerical data as unimodel or bimodal.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
<li class="nav-item">
    <a class="nav-link" href="../../license.html">
<p>License</p>
</a>
  </li>  
</ul>
</div>
  </div>
</footer>


</body></html>