<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Stat 20 - Summarizing Numerical Associations</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../2-summarizing-data/07-multiple-linear-regression/notes.html" rel="next">
<link href="../../2-summarizing-data/03-a-grammar-of-graphics/notes.html" rel="prev">
<link href="../../assets/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-WP7F4QKDC8"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-WP7F4QKDC8', { 'anonymize_ip': true});
</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="Stat 20 - Summarizing Numerical Associations">
<meta property="og:description" content="Overplotting, correlation and the least squares line">
<meta property="og:image" content="https://stat20.berkeley.edu/summer-2024/2-summarizing-data/06-summarizing-associations/images/association.png">
<meta property="og:site_name" content="Stat 20">
<meta property="og:image:height" content="346">
<meta property="og:image:width" content="476">
<meta name="twitter:title" content="Stat 20 - Summarizing Numerical Associations">
<meta name="twitter:description" content="Overplotting, correlation and the least squares line">
<meta name="twitter:image" content="https://stat20.berkeley.edu/summer-2024/2-summarizing-data/06-summarizing-associations/images/association.png">
<meta name="twitter:image-height" content="346">
<meta name="twitter:image-width" content="476">
<meta name="twitter:card" content="summary_large_image">
</head>
<body class="nav-sidebar floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-sm " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/stat20-hex-small.png" alt="Stat 20 logo" class="navbar-logo"></a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../office-hours.html"> 
<span class="menu-text">Office Hours</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../notes.html" aria-current="page"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../assignments.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools tools-wide">
    <a href="https://edstem.org/us/courses/51198" title="" class="quarto-navigation-tool px-1" aria-label="Ed Discussion Forum"><i class="bi bi-chat-fill"></i></a>
    <a href="https://www.gradescope.com/courses/693050" title="" class="quarto-navigation-tool px-1" aria-label="Gradescope"><i class="bi bi-bar-chart-fill"></i></a>
    <a href="https://stat20.datahub.berkeley.edu/" title="" class="quarto-navigation-tool px-1" aria-label="RStudio"><i class="bi bi-r-circle-fill"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../2-summarizing-data/06-summarizing-associations/notes.html">Summarizing Numerical Associations</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../1-questions-and-data/01-understanding-the-world/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Understanding the World with Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../1-questions-and-data/02-taxonomy-of-data/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Taxonomy of Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/01-summarizing-categorical-data/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarizing Categorical Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/02-summarizing-numerical-data/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarizing Numerical Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/04-conditioning/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Pipelines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/03-a-grammar-of-graphics/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A Grammar of Graphics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/06-summarizing-associations/notes.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Summarizing Numerical Associations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/07-multiple-linear-regression/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/01-chance-intro/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducing Probability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/02-cond-prob-indep/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computing Probabilities</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/03-probability-dsns/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability Distributions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/04-random-variables/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Random Variables</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/05-ev-se/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Expected value and variance of a random variable</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/06-normal-approx/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Continuous Distributions and Normal Approximations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/01-sampling-distributions/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">From Samples to Populations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/02-confidence-intervals/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Confidence Intervals</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/03-bootstrapping/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrapping</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/04-hypothesis-tests/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/05-hypothesis-tests-2/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis Tests II</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/06-wrong-by-design/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wrong by Design</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../6-prediction/01-method-of-least-squares/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Method of Least Squares</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../6-prediction/02-improving-predictions/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluating and Improving Predictions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../6-prediction/03-overfitting/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overfitting</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../6-prediction/05-logistic-regression/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logistic Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../5-causation/01-defining-causality/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Defining Causality</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../5-causation/02-experiments/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Randomized Experiments</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../5-causation/03-matching/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Causal Effects in Observational Studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../5-causation/04-time/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using Time to Measure Causal Effects</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#overplotting" id="toc-overplotting" class="nav-link active" data-scroll-target="#overplotting">Overplotting</a></li>
  <li>
<a href="#associations-and-the-correlation-coefficient" id="toc-associations-and-the-correlation-coefficient" class="nav-link" data-scroll-target="#associations-and-the-correlation-coefficient">Associations and the correlation coefficient</a>
  <ul class="collapse">
<li><a href="#the-correlation-coefficient" id="toc-the-correlation-coefficient" class="nav-link" data-scroll-target="#the-correlation-coefficient">The Correlation Coefficient</a></li>
  <li><a href="#example-poverty-and-graduation-rate" id="toc-example-poverty-and-graduation-rate" class="nav-link" data-scroll-target="#example-poverty-and-graduation-rate">Example: Poverty and Graduation rate</a></li>
  </ul>
</li>
  <li>
<a href="#the-simple-linear-model" id="toc-the-simple-linear-model" class="nav-link" data-scroll-target="#the-simple-linear-model">The Simple Linear Model</a>
  <ul class="collapse">
<li><a href="#the-least-squares-line" id="toc-the-least-squares-line" class="nav-link" data-scroll-target="#the-least-squares-line">The Least Squares Line</a></li>
  <li><a href="#interpreting-the-slope-and-intercept" id="toc-interpreting-the-slope-and-intercept" class="nav-link" data-scroll-target="#interpreting-the-slope-and-intercept">Interpreting the slope and intercept</a></li>
  <li><a href="#residuals" id="toc-residuals" class="nav-link" data-scroll-target="#residuals">Residuals</a></li>
  </ul>
</li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="notes.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Summarizing Numerical Associations</h1>
<p class="subtitle lead">Overplotting, correlation and the least squares line</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p><span class="dropcap">W</span>hen we first discussed constructing summaries for numerical data, you may have noticed that we left out the case when we are working with two numerical variables. This is a <em>very</em> common scenario in statistics and data science– so much so that it deserves its own set of notes! In this lecture, we will discuss how we can make visualizations and calculate summary statistics involving two numerical variables. Then, we will introduce a third method of describing data: building a <strong>model</strong>.</p>
<section id="overplotting" class="level2"><h2 class="anchored" data-anchor-id="overplotting">Overplotting</h2>
<p>First, we should spotlight an issue that can arise when visualizing numerical associations. This issue may have the potential to hide an association between them if it is not treated.</p>
<p>Let’s examine the class survey dataset from earlier in this course. Stat 20 students filled out a survey that asked them their opinion on several topics including:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/q-tech.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="500"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/q-crypto.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="500"></p>
</figure>
</div>
<p>The result was a data frame with 619 rows (one for every respondent) and 2 columns of discrete numerical data. A natural way to visualize this data is by creating a <strong>scatter plot.</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>The eye is immediately drawn to the eerie geometric regularity of this data. Isn’t real data messier than this? What’s going on?</p>
<p>A hint is in the sample size. The number of observations in the data set was over 600 and yet the number of points shown here is just a bit under 100. Where did those other observations go?</p>
<p>It turns out they are in this plot, <em>they’re just piled on top of one another!</em> Since there are only 10 possible values for each question, many students ended up selecting the same values for both, leading their points to be drawn on top of one another.</p>
<p>This phenomenon is called <strong>overplotting</strong> and it is very common in large data sets. There are several strategies for dealing with it, but here we cover two of them.</p>
<p>One approach to fixing the problem of points piled on top of one another is to unpile them by adding just a little bit of random noise to their x- and y-coordinate. This technique is called <strong>jittering</strong> and can be done in <code>ggplot2</code> by replacing <code>geom_point()</code> with <strong><code>geom_jitter()</code></strong>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">class_survey</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">tech</span>,</span>
<span>                         y <span class="op">=</span> <span class="va">crypto</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_jitter</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Technology is destructive to relationships"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"cryptocurrency will play a\n dominant role in finance"</span>,</span>
<span>         title <span class="op">=</span> <span class="st">"No association between opinions on technology and \n cryptocurrency"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Ahh . . . there are those previously hidden students. Interestingly, the title on the first plot still holds true: even when we’re looking at <em>all</em> of the students, there doesn’t appear to be much of a pattern. That is certainly not the case in all overplotted data sets! Often overplotting will obscure a pattern that jumps out after the overplotting has been attended to.</p>
<p>The second technique is to make the points transparent by changing an aesthetic attribute (setting) called the <strong>alpha value.</strong> Let’s combine transparency with jittering to understand the effect.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">class_survey</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">tech</span>,</span>
<span>                         y <span class="op">=</span> <span class="va">crypto</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">geom_jitter</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">.3</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Technology is destructive to relationships"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"cryptocurrency will play a\n dominant role in finance"</span>,</span>
<span>         title <span class="op">=</span> <span class="st">"No association between opinions on technology and \n cryptocurrency"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>The <code>alpha</code> argument runs between 0 and 1, where 1 is fully opaque and 0 is fully see-through. Here, <code>alpha = .3</code>, which changes all observations from black to gray. Where the points overlap, their alpha values add to create a dark blob.</p>
<p>There’s still no sign of a strong association between these variables, but at least, by taking overplotting into consideration, we’ve made that determination after incorporating all of the data.</p>
</section><section id="associations-and-the-correlation-coefficient" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="associations-and-the-correlation-coefficient">Associations and the correlation coefficient</h2>
<p><span class="dropcap">W</span>hich of the following plots do you think depicts the relationship between the high school graduation rate and the poverty rate among the 50 US states?</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="595"></p>
</figure>
</div>
</div>
</div>
<p>If you guessed the plot on the left, you are correct <span class="emoji" data-emoji="tada">🎉</span>.</p>
<p>States with higher poverty rates tend to have lower graduation rates. This is a prime example of two variables that are <em>associated</em>. In a previous set of notes we defined association between two categorical variables, but lets replace that with a more general definition that can apply here.</p>
<dl>
<dt><strong>Association</strong></dt>
<dd>
There is an association between two variables if the conditional distribution of one varies as you move across values of the other.
</dd>
</dl>
<p>You can detect associations in scatter plots by scanning from left to right along the x-axis and determining whether or not the conditional distribution of the y-variable is changing or not. In the figure to the left below, when you look first to the states with low poverty rates (in the blue box), you find that the conditional distribution of the graduation rate (represented by the blue density curve along the right side of the scatter plot) is high: most of those states have graduation rates between 85% and 90%. When you scan to the right in that scatter plot, and condition on having a high poverty rate (the states in the red box), the conditional distribution shifts downwards. Those states have graduations rates in the low 80%s.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>These density curves are conditional distributions because we’ve set a condition on the data we’re visualizing. When focusing on the data that’s in the blue box, for example, we’ve in effect set up a filter where Poverty &lt; 9.</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="720"></p>
</figure>
</div>
</div>
</div>
<p>The plot on the right, by contrast, exhibits no association between poverty rate and graduation rate. When we compare the low poverty states with the high poverty states, their conditional distributions of Graduation rate are essentially the same.</p>
<p>So we can use the simple scatter plot to determine whether or not two numerical variables are associated, but sometimes a graphic isn’t enough. In these notes we’ll move from graphical summaries to numerical summaries and construct two different approaches to capturing these associations in numbers: the correlation coefficient and the simple linear model.</p>
<section id="the-correlation-coefficient" class="level3 page-columns page-full"><h3 class="anchored" data-anchor-id="the-correlation-coefficient">The Correlation Coefficient</h3>
<p>Let’s set out to engineer our first numerical summary in the same manner that we have previously, by laying out the properties that we’d like our summary to have.</p>
<p>Please watch the following 12 minute video.</p>
<p><a href="https://bcourses.berkeley.edu/courses/1531766/external_tools/90481"><img src="images/vid-thumbnail.png" class="img-fluid" width="400"></a></p>
<dl>
<dt><strong>Correlation coefficient, <span class="math inline">\(r\)</span></strong></dt>
<dd>
The correlation coefficient, <span class="math inline">\(r\)</span>, between two variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is <span class="math display">\[r = \frac{1}{n-1}\sum_{i=1}^n \left( \frac{x_i - \bar{x}}{s_x} \right) \left( \frac{y_i - \bar{y}}{s_y} \right)\]</span>
</dd>
</dl>

<div class="no-row-height column-margin column-container"><div class="">
<p>Several different statistics have been proposed for measuring association. This is the most common and is more specifically called the Pearson correlation.</p>
</div></div></section><section id="example-poverty-and-graduation-rate" class="level3"><h3 class="anchored" data-anchor-id="example-poverty-and-graduation-rate">Example: Poverty and Graduation rate</h3>
<p>The data frame used to create the scatter plot above on the left looks like this.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 51 × 2
   Graduates Poverty
       &lt;dbl&gt;   &lt;dbl&gt;
 1      79.9    14.6
 2      90.6     8.3
 3      83.8    13.3
 4      80.9    18  
 5      81.1    12.8
 6      88.7     9.4
 7      87.5     7.8
 8      88.7     8.1
 9      86      16.8
10      84.7    12.1
# ℹ 41 more rows</code></pre>
</div>
</div>
<p>Since it is a data frame, we can use the <code>summarize()</code> function to calculate our summary statistic.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">poverty</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>r <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">Poverty</span>, <span class="va">Graduates</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
       r
   &lt;dbl&gt;
1 -0.747</code></pre>
</div>
</div>
<p>The value of -0.747 tells us that the linear association between these variables is negative and reasonably strong. This is our first example of a <em>bivariate</em> summary statistic: there are two variables that we put inside the <code><a href="https://rdrr.io/r/stats/cor.html">cor()</a></code> function to compute our statistic.</p>
<p>Let’s repeat this calculation for the data frame that created the shapeless scatter plot with no association, <code>poverty_shuffled</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">poverty_shuffled</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>r <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">Poverty</span>, <span class="va">Graduates</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
        r
    &lt;dbl&gt;
1 -0.0546</code></pre>
</div>
</div>
<p>As expected, that scatter plot yields a correlation coefficient very close to zero because the points are scattered across all four quadrants of the plot.</p>
</section></section><section id="the-simple-linear-model" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="the-simple-linear-model">The Simple Linear Model</h2>
<p>Another approach to summarizing the linear association is to just … draw a line.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/handdrawn-line.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="300"></p>
</figure>
</div>
<p>This line serves both as a graphical summary and <em>also</em> as a numerical summary. After all, every line that you draw on a scatter plot is defined by two numbers: the slope and the y-intercept. This line is called a <em>simple linear model</em>.</p>
<dl>
<dt><strong>Simple Linear Model</strong></dt>
<dd>
An expression for a possible value of the <span class="math inline">\(y\)</span> variable, <span class="math inline">\(\hat{y}\)</span>, as a linear function of the <span class="math inline">\(x\)</span> variable with slope <span class="math inline">\(b_1\)</span> and y-intercept <span class="math inline">\(b_0\)</span>. <span class="math display">\[\hat{y} = b_0 + b_1x\]</span>
</dd>
</dl>
<p>Therefore, a simple linear model captures the linear relationship of two variables in not one but <em>two</em> summary statistics, <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>.</p>
<p>For the line above, we can do our best to eye-ball these. The line appears to rise -2 percentage points for every 2.5 that it runs, so I’d estimate the slope to be about <span class="math inline">\(-2/2.5 = -0.8\)</span>. If I were to draw the line all the way to the left until it crossed the y-axis at a poverty rate of 0, its y-intercept would be around 95. So I could express the line that is drawn above as:</p>
<p><span class="math display">\[\hat{y} = 95 - 0.8 x\]</span></p>
<section id="the-least-squares-line" class="level3"><h3 class="anchored" data-anchor-id="the-least-squares-line">The Least Squares Line</h3>
<p>If that felt a little shifty to you - drawing a line by hand and then eyeballing its slope and intercept - we can be more precise by using a more precisely-defined type of linear model: the least squares line. This is a method that we’ll study in depth when we get to the unit on prediction, but for now, we’ll use it because it makes calculation very easy. You can find the slope and intercept of the least squares line using statistics that we’re already familiar with: <span class="math inline">\(\bar{x}, \bar{y}, s_x, x_y\)</span>, and <span class="math inline">\(r\)</span>.</p>
<dl>
<dt><strong>Least Squares Slope</strong></dt>
<dd>
<span class="math display">\[ b_1 = r \frac{s_y}{s_x} \]</span>
</dd>
<dt><strong>Least Squares Intercept</strong></dt>
<dd>
<span class="math display">\[ b_0 = \bar{y} - b_1 \bar{x}\]</span>
</dd>
</dl>
<!-- Give a bit of instuition for where these come from --><p>So how does this line look compared to the hand-drawn line? Let’s calculate the slope and intercept. In R, we can do this with a function called <strong><code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>.</strong> To see the slope and intercept for our model, we can print out our model object.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">Graduates</span> <span class="op">~</span> <span class="va">Poverty</span>, data <span class="op">=</span> <span class="va">poverty</span><span class="op">)</span></span>
<span><span class="va">m1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Graduates ~ Poverty, data = poverty)

Coefficients:
(Intercept)      Poverty  
    96.2022      -0.8979  </code></pre>
</div>
</div>
<p>The syntax for <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> uses what’s called “formula notation” in R. The first argument is a formula of the form <code>y ~ x</code> and can be read as, “Explain the y as a function of the x”. In the second argument, you specify which data frame contains the variables used in the formula. If we want to use to save this slope and intercept for later use, we can save it into an object, just like a data frame or a vector can be saved.</p>
<p>We can then add our model to our scatter plot. This can be done with the <strong><code>geom_smooth()</code></strong> layer in <code>ggplot2</code> and the <code>method = "lm"</code> argument (you do not need to worry about the purpose of the <code>se</code> argument).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">poverty</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">Poverty</span>, </span>
<span>                    y <span class="op">=</span> <span class="va">Graduates</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Poverty Rate"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Graduation Rate"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
<p>That works remarkably well!</p>
</section><section id="interpreting-the-slope-and-intercept" class="level3"><h3 class="anchored" data-anchor-id="interpreting-the-slope-and-intercept">Interpreting the slope and intercept</h3>
<p>So if the correlation coefficient measures the strength of the linear relationship between two variables, what exactly are the slope and intercept of a linear model between involving these two variables measuring?</p>
<p><strong>The slope captures the expected change in the <span class="math inline">\(y\)</span> variable associated with the <span class="math inline">\(x\)</span> variable changing by 1 unit.</strong> In this example, states that are separated by 1 percentage point in their poverty rate tend to be separated by about -.89 in their graduation rate. This is distinct from what the correlation tells us because while <span class="math inline">\(r\)</span> will stay the same regardless of the units in which the data is measured, <span class="math inline">\(b_1\)</span> is expressly designed to tell us how those units of measurement relate to one another.</p>
<p>What about the intercept? <strong>It tells us the value that we’d expect the <span class="math inline">\(y\)</span> to take when the <span class="math inline">\(x\)</span> takes a value of zero.</strong> <em>Sometimes that’s an informative statistic, sometime it is not.</em> In this setting, do you really expect the graduation rate to be around 96% when their poverty rate is zero? What would it even look like for a state to have a poverty rate of zero? The abstraction of the linear model allows us to ponder such a world, but the reality of economics in the US is that we would never actually observe poverty rates of zero.</p>
<p>So what good is the intercept? Well, it’s useful in helping us calculate a <strong>residual.</strong></p>
</section><section id="residuals" class="level3 page-columns page-full"><h3 class="anchored" data-anchor-id="residuals">Residuals</h3>
<p>One of the benefits of explaining the association between two variables with a line instead of just the correlation coefficient is that it allows us to calculate what we would <em>expect</em> an observation’s y-value to be based on its x value, so that we can see how far our expectation is from reality. That gap between expectation and reality is called a <em>residual</em>.</p>
<dl>
<dt>
<strong>Residual</strong> (<span class="math inline">\(\hat{e}_i\)</span>)</dt>
<dd>
The difference between the observed value of a data point, <span class="math inline">\(y_i\)</span>, and the value that we would expect according to a linear model, <span class="math inline">\(\hat{y}_i\)</span>. <span class="math display">\[ \hat{e}_i = y_i - \hat{y}_i \]</span>
</dd>
</dl>

<div class="no-row-height column-margin column-container"><div class="">
<p><span class="math inline">\(\hat{y}_i\)</span> is said “y hat sub i” and is also called the “fitted value”.</p>
</div></div><p>Let’s calculate the residual for California. Here is that row in the data set.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">poverty</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">State</span> <span class="op">==</span> <span class="st">"California"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">State</span>, <span class="va">Graduates</span>, <span class="va">Poverty</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  State      Graduates Poverty
  &lt;chr&gt;          &lt;dbl&gt;   &lt;dbl&gt;
1 California      81.1    12.8</code></pre>
</div>
</div>
<p>This shows us that for California, <span class="math inline">\(y = 81.1\)</span>, so the next step is to find where the line passes through California’s x-value, <span class="math inline">\(x = 12.8\)</span>. There are several ways to do that calculation, including using R like a calculator and simply plugging that value into the equation for the line show above.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">y_hat</span> <span class="op">&lt;-</span> <span class="fl">96.2022</span> <span class="op">-</span> <span class="fl">0.8979</span> <span class="op">*</span> <span class="fl">12.8</span></span>
<span><span class="va">y_hat</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 84.70908</code></pre>
</div>
</div>
<p>With that in hand, we can calculate California’s residual.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fl">81.1</span> <span class="op">-</span> <span class="va">y_hat</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3.60908</code></pre>
</div>
</div>
<p>This residual tells us that California is actually a bit of an underachiever. Among states with a poverty rate around 12.8, we would expect their graduate rate to be around 84.7. California’s rate, however, is 81.1, a decrease of 3.6.</p>
<p>The calculation of the residual can be seen in the plot below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>The horizontal dashed line represents <span class="math inline">\(\hat{y} = 84.7\)</span>, the y-value of the least squares line when it passes through <span class="math inline">\(x = 12.8\)</span>. The vertical red dashed line is the residual: the distance between the line and the observation in the y direction.</p>
<p>Residuals open up a new avenue for numerical statistics. While the slope and intercept are two statistics that tell us about the <em>overall</em> linear relationship between the two variables, each residual is a statistic that tells us whether an <em>individual</em> observation’s y-value is higher or lower than we’d expect based on its x-value.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>If you have <span class="math inline">\(n\)</span> data points, you can calculate <span class="math inline">\(n\)</span> residuals. This is described below.</p>
</div></div><p>While using R as a calculator directly to obtain <em>one</em> residual is somewhat efficient, this changes when you would like to calculate a residual for each point in your data set. Imagine having to write <span class="math inline">\(n\)</span> lines of code, one for each observation: <span class="math inline">\(y_1\)</span>, <span class="math inline">\(y_2\)</span>, and all the way to <span class="math inline">\(y_n\)</span>! Luckily, when you save a linear model into an object, you store lots of useful information, including <span class="math inline">\(\hat{y}_i\)</span> and <span class="math inline">\(\hat{e}_i\)</span> for every observation <span class="math inline">\(y_i\)</span>. These can be accessed via the <code><a href="https://rdrr.io/r/stats/fitted.values.html">fitted()</a></code> and <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code> functions, respectively.</p>
<p><code><a href="https://rdrr.io/r/stats/fitted.values.html">fitted()</a></code> and <code><a href="https://rdrr.io/r/stats/residuals.html">residuals()</a></code> return vectors. To match the vectors up with the observations, we can <em>mutate</em> them as columns onto the original data frame. From here, we can isolate the residual for the state of California as before.</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">poverty</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>y_hat <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">m1</span><span class="op">)</span>,</span>
<span>         e_hat <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">m1</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">State</span>, <span class="va">Graduates</span>, <span class="va">Poverty</span>, <span class="va">y_hat</span>, <span class="va">e_hat</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">State</span> <span class="op">==</span> <span class="st">"California"</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  State      Graduates Poverty y_hat e_hat
  &lt;chr&gt;          &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 California      81.1    12.8  84.7 -3.61</code></pre>
</div>
</div>
</section></section><section id="summary" class="level2"><h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>In these notes we considered the question of how to capture the association between two variables with both visualizations and numerical summary statistics. The <strong>correlation coefficient</strong> is one of the most common statistics to use in this case: it captures the strength and direction of the linear trend. This statistic can be used, along with other simple summary statistics, to calculate the slope and intercept of the <strong>least squares line</strong>. The least squares line is an alternative approach to summarizing the linear relationship between two numerical variables. It has the advantage of providing an expectation for the y-value of every observation, which allows us to calculate residuals which are expressions of whether each observation is higher or lower than we’d expect.</p>
<p>We’ll spend time practicing calculating these statistics - and looking at lots of scatter plots - in class.</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../2-summarizing-data/03-a-grammar-of-graphics/notes.html" class="pagination-link  aria-label=" a="" grammar="" of="" graphics="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">A Grammar of Graphics</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../2-summarizing-data/07-multiple-linear-regression/notes.html" class="pagination-link" aria-label="Multiple Linear Regression">
        <span class="nav-page-text">Multiple Linear Regression</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
<li class="nav-item">
    <a class="nav-link" href="../../license.html">
<p>License</p>
</a>
  </li>  
</ul>
</div>
  </div>
</footer>


</body></html>