<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Stat 20 - Summarizing Categorical Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../2-summarizing-data/02-summarizing-numerical-data/notes.html" rel="next">
<link href="../../1-questions-and-data/02-taxonomy-of-data/notes.html" rel="prev">
<link href="../../assets/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script><link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="Stat 20 - Summarizing Categorical Data">
<meta property="og:description" content="From data frames to tables. From tables to bar charts.">
<meta property="og:image" content="https://www.stat20.org/2-summarizing-data/01-summarizing-categorical-data/images/two-var-small.png">
<meta property="og:site_name" content="Stat 20">
<meta property="og:image:height" content="492">
<meta property="og:image:width" content="776">
<meta name="twitter:title" content="Stat 20 - Summarizing Categorical Data">
<meta name="twitter:description" content="From data frames to tables. From tables to bar charts.">
<meta name="twitter:image" content="https://www.stat20.org/2-summarizing-data/01-summarizing-categorical-data/images/two-var-small.png">
<meta name="twitter:image-height" content="492">
<meta name="twitter:image-width" content="776">
<meta name="twitter:card" content="summary_large_image">
</head>
<body class="nav-sidebar floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-sm " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/stat20-hex-small.png" alt="Stat 20 logo" class="navbar-logo"></a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../office-hours.html"> 
<span class="menu-text">Office Hours</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../notes.html" aria-current="page"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../assignments.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools tools-wide">
    <a href="https://edstem.org/us/courses/51198" title="" class="quarto-navigation-tool px-1" aria-label="Ed Discussion Forum"><i class="bi bi-chat-fill"></i></a>
    <a href="https://www.gradescope.com/courses/693050" title="" class="quarto-navigation-tool px-1" aria-label="Gradescope"><i class="bi bi-bar-chart-fill"></i></a>
    <a href="https://stat20.datahub.berkeley.edu/" title="" class="quarto-navigation-tool px-1" aria-label="RStudio"><i class="bi bi-r-circle-fill"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../2-summarizing-data/01-summarizing-categorical-data/notes.html">Summarizing Categorical Data</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../1-questions-and-data/01-understanding-the-world/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Understanding the World with Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../1-questions-and-data/02-taxonomy-of-data/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Taxonomy of Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/01-summarizing-categorical-data/notes.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Summarizing Categorical Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/02-summarizing-numerical-data/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarizing Numerical Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/04-conditioning/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Pipelines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/03-a-grammar-of-graphics/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A Grammar of Graphics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/06-summarizing-associations/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarizing Numerical Associations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../2-summarizing-data/07-multiple-linear-regression/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/01-chance-intro/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducing Probability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/02-cond-prob-indep/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computing Probabilities</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/03-probability-dsns/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability Distributions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/04-random-variables/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Random Variables</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/05-ev-se/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Expected value and variance of a random variable</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../3-probability/06-normal-approx/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Continuous Distributions and Normal Approximations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/01-sampling-distributions/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">From Samples to Populations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/02-confidence-intervals/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Confidence Intervals</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/03-bootstrapping/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrapping</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/04-hypothesis-tests/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/05-hypothesis-tests-2/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis Tests II</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../4-generalization/06-wrong-by-design/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wrong by Design</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../6-prediction/01-method-of-least-squares/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Method of Least Squares</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../6-prediction/02-improving-predictions/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluating and Improving Predictions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../6-prediction/03-overfitting/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overfitting</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../6-prediction/05-logistic-regression/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logistic Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../5-causation/01-defining-causality/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Defining Causality</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../5-causation/02-experiments/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Randomized Experiments</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../5-causation/03-matching/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Causal Effects in Observational Studies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../5-causation/04-time/notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using Time to Measure Causal Effects</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#welcome-to-unit-i-summarizing-data" id="toc-welcome-to-unit-i-summarizing-data" class="nav-link active" data-scroll-target="#welcome-to-unit-i-summarizing-data">Welcome to Unit I: Summarizing Data</a></li>
  <li>
<a href="#summarizing-categorical-data" id="toc-summarizing-categorical-data" class="nav-link" data-scroll-target="#summarizing-categorical-data">Summarizing Categorical Data</a>
  <ul class="collapse">
<li><a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables">Contingency tables</a></li>
  <li><a href="#from-counts-to-proportions" id="toc-from-counts-to-proportions" class="nav-link" data-scroll-target="#from-counts-to-proportions">From Counts to Proportions</a></li>
  <li><a href="#identifying-an-association" id="toc-identifying-an-association" class="nav-link" data-scroll-target="#identifying-an-association">Identifying an association</a></li>
  </ul>
</li>
  <li>
<a href="#the-ideas-in-code" id="toc-the-ideas-in-code" class="nav-link" data-scroll-target="#the-ideas-in-code">The Ideas in Code</a>
  <ul class="collapse">
<li><a href="#help-and-arguments" id="toc-help-and-arguments" class="nav-link" data-scroll-target="#help-and-arguments">Help and Arguments</a></li>
  <li><a href="#libraries" id="toc-libraries" class="nav-link" data-scroll-target="#libraries">Libraries</a></li>
  <li><a href="#a-first-visualization-with-ggplot2" id="toc-a-first-visualization-with-ggplot2" class="nav-link" data-scroll-target="#a-first-visualization-with-ggplot2">A first visualization with <code>ggplot2</code></a></li>
  </ul>
</li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="notes.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Summarizing Categorical Data</h1>
<p class="subtitle lead">From data frames to tables. From tables to bar charts.</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p><br></p>
<section id="welcome-to-unit-i-summarizing-data" class="level2" style="text-align: center"><h2 class="anchored" data-anchor-id="welcome-to-unit-i-summarizing-data">Welcome to Unit I: Summarizing Data</h2>
</section><p>In spring of 2022, the New York Times ran the following story<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<div id="fig-inflation" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-inflation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/nyt-inflation.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="500">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-inflation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: An article from the New York times entitled consumer prices are still climbing rapidly with an associated line graph showing the inflation rate (as measured by the change in the consumer price index) over the last 40 years with a spike upwards in spring of 2022.
</figcaption></figure>
</div>
<p>“Consumer Prices” refers to the Consumer Price Index<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, a weighted average of the prices of thousands of everyday consumer goods: sports equipment, soft drinks, sneakers, internet service, etc. An increase in that index is thought to correspond to rising inflation.</p>
<p>Look carefully at the line plot. Which of the following four claims does it support?</p>
<ol type="1">
<li>The CPI rose 8.3% in April, 2022.</li>
<li>The CPI will likely rise throughout the summer of 2022.</li>
<li>The global consumer price index rose in April, 2022.</li>
<li>The CPI rose 8.3% because of the war in Ukraine.</li>
</ol>
<p>In truth, this plot could be consistent with all these claims. They are, in turn, a summary, a prediction, a generalization, and a causal claim. This newspaper headline falls squarely in the first category, a <strong>summary</strong>, which seeks only to describe the data set that is on hand.</p>
<p>Although 8.3% seems like a simple enough number, it is actually <em>summarizing</em> a vast data set of thousands of prices. The process of describing a data set invariably involves summarizing it, either with <strong>numerical summaries</strong> like 8.3% or with <strong>graphical summaries</strong> like the line plot show above.</p>
<p>In this unit, we will learn to critique and construct descriptive claims made with data. Although they sound elementary, descriptive claims are the most common form of claim made using data. They have the power to move, if not mountains, at least markets.</p>
<div id="fig-claims" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-claims-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/claims-only.png" class="img-fluid figure-img" width="500">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-claims-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Four types of claims made with data covered in this class.
</figcaption></figure>
</div>
<section id="summarizing-categorical-data" class="level2"><h2 class="anchored" data-anchor-id="summarizing-categorical-data">Summarizing Categorical Data</h2>
<p><span class="dropcap">T</span>he tools for calculating numerical summaries and graphical summaries can be cleanly divided between tools developed for categorical data and tools for numerical data. We’ll discuss each in turn, starting with categorical data.</p>
<p>When Dr.&nbsp;Gorman collected data near Palmer Station, Antarctica, she recorded a total of eight variables on 333 penguins, presented here in a data frame.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 333 × 8
   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
   &lt;fct&gt;   &lt;fct&gt;              &lt;dbl&gt;         &lt;dbl&gt;             &lt;int&gt;       &lt;int&gt;
 1 Adelie  Torgersen           39.1          18.7               181        3750
 2 Adelie  Torgersen           39.5          17.4               186        3800
 3 Adelie  Torgersen           40.3          18                 195        3250
 4 Adelie  Torgersen           36.7          19.3               193        3450
 5 Adelie  Torgersen           39.3          20.6               190        3650
 6 Adelie  Torgersen           38.9          17.8               181        3625
 7 Adelie  Torgersen           39.2          19.6               195        4675
 8 Adelie  Torgersen           41.1          17.6               182        3200
 9 Adelie  Torgersen           38.6          21.2               191        3800
10 Adelie  Torgersen           34.6          21.1               198        4400
# ℹ 323 more rows
# ℹ 2 more variables: sex &lt;fct&gt;, year &lt;int&gt;</code></pre>
</div>
</div>
<p>The first two of these you’ll recognize as <em>nominal categorical</em> variables. The <code>species</code> of each penguin can take one of three levels: Adelie, Chinstrap, or Gentoo; and the <code>island</code> on which they were found can also take three levels: Biscoe, Dream, or Torgersen.</p>
<section id="contingency-tables" class="level3"><h3 class="anchored" data-anchor-id="contingency-tables">Contingency tables</h3>
<p>If I asked you to look at this data frame and describe what these two variables show, that’s a surprisingly difficult task! The raw data frame has simply too much information to process at a glance. To make it easier, we need to consolidate all of that information into a few numerical summaries. Since these variables don’t take numbers as values, we can’t take an average or a median. What we can do, though, is simply count up the number of penguins that appeared in every combination of levels and lay them out in a table like this:</p>
<!-- Remake very polished tables using gt -->
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;"></th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Biscoe</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Dream</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Torgersen</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Adelie</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">47</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Chinstrap</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Gentoo</td>
<td style="text-align: right;">119</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<p>After a few moments of looking at this table, a few features emerge:</p>
<ol type="1">
<li>The Chinstrap penguins were only found on Dream island.</li>
<li>Adelie penguins are the most common.</li>
<li>The most prevalent penguin type in this data set was a Gentoo from Biscoe Island.</li>
</ol>
<p>This method of displaying data is called a contingency table.</p>
<dl>
<dt><strong>Contingency table</strong></dt>
<dd>
A table that shows the counts or frequencies of observations that occur in every combination of levels of two categorical variables. Used to display the relationship between variables.
</dd>
</dl>
<p>We can also opt to present these counts in graphical form by constructing a <strong>bar chart</strong>. There are two common methods for laying out counts across two variables in a bar chart.</p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Stacked bar chart</figcaption></figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Dodged bar chart</figcaption></figure>
</div>
</div>
</div>
</div>
<p>The stacked bar chart puts one of the variables along the x-axis (the species) and fills up the y-axis according to the counts in each level of the other variable (the island). The side-by-side bar chart is similar, but unstacks the “Adelie” bar to put the three islands besides one another.</p>
<p>So with two similar to charts to choose from, which one should you pick? The stacked bar chart succeeds in highlighting the total number of Adelie penguins: 146 (also the sum of the top row of the contingency table). The side-by-side version makes that total harder to see, but it is easier to see at a glance the relative sizes of which islands each of those Adelie penguins came from.</p>
<div id="fig-two-var" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center" alt="Sketch showing the flow for two variables from raw data to contingency table to barchart.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-two-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/two-var.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Sketch showing the flow for two variables from raw data to contingency table to barchart." width="550">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: A schematic showing the link between a data frame, a contingency table of counts, and a stacked bar chart for a subset of 16 of the 333 penguins.
</figcaption></figure>
</div>
</section><section id="from-counts-to-proportions" class="level3"><h3 class="anchored" data-anchor-id="from-counts-to-proportions">From Counts to Proportions</h3>
<p>When you count the number of observations in each level of a categorical variable, you’re encoding the overall magnitude of each. But often what is more important is the <em>relative</em> magnitude of each. We can emphasize this by converting counts into proportions.</p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="lightable-paper table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;"></th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Biscoe</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Dream</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Torgersen</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Adelie</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">47</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Chinstrap</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Gentoo</td>
<td style="text-align: right;">119</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">


</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="lightable-paper table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;"></th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Biscoe</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Dream</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Torgersen</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Adelie</td>
<td style="text-align: right;">0.132</td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">0.142</td>
<td style="text-align: right; font-weight: bold; border-left: 1px solid;">0.439</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Chinstrap</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right; font-weight: bold; border-left: 1px solid;">0.204</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Gentoo</td>
<td style="text-align: right;">0.357</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right; font-weight: bold; border-left: 1px solid;">0.357</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-right: 1px solid; font-weight: bold;"></td>
<td style="text-align: right; font-weight: bold;">0.489</td>
<td style="text-align: right; font-weight: bold;">0.369</td>
<td style="text-align: right; font-weight: bold;">0.142</td>
<td style="text-align: right; font-weight: bold; border-left: 1px solid; font-weight: bold;">1.000</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">


</div>
</div>
</div>
<p>The second table contains two different types of proportions that can be found in the middle and margins of the table, respectively.</p>
<dl>
<dt><strong>Joint Proportion</strong></dt>
<dd>
The proportion of observations of multiple variables that appear in a combination of levels of those variables. E.g. 44 / 333 = .132, the proportion of all 333 penguins that were Adelie and from Biscoe.
</dd>
<dt><strong>Marginal Proportion</strong></dt>
<dd>
The proportion of observations in one variable that appear in a single level of that variable. E.g. (44 + 119) / 333 = .489, the proportion of all penguins that were from Biscoe.
</dd>
</dl>
<p>From these proportions we can derive a third type of proportion.</p>
<dl>
<dt><strong>Conditional Proportion</strong></dt>
<dd>
The proportion of observations in one level of one variable that appear in a level of a second variable. E.g. .132 / .489 = .269, the proportion of penguins from Biscoe that were Adelie.
</dd>
</dl>
<p>These distinctions are important because often a subtle change in language can result in a dramatically different number. Revisit the observations made about the original table of counts:</p>
<ol type="1">
<li>The Chinstrap penguins were only found on Dream Island.</li>
<li>Adelie penguins were the most common.</li>
<li>The most prevalent penguin type in this data set was a Gentoo from Biscoe Island.</li>
</ol>
<p>The first observation refers to a conditional proportion: of the 68 total Chinstrap penguins, 68 of them were on Dream (a proportion of 1). The second refers to a marginal proportion: .439 of the penguins were Adelie versus .204 Chinstrap and .357 Gentoo. The third is a joint proportion: .357, or 124 out of all 333 penguins were Gentoos living on Biscoe.</p>
<p>With these distinctions in hand, we can construct a useful variant of the bar chart: the normalized stacked bar chart.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Instead of plotting raw counts, a normalized bar chart plots proportions. But which proportions?</p>
<p>If you look back and forth between this bar chart and the table of proportions, you’ll eventually decide that this bar chart is showing conditional proportions. The height of the blue bar in the lower left corner indicates the proportion of all Adelie penguins that were from Torgersen: 47 / 146 = .322. Since <code>species</code> is in the denominator of this proportion, we say that we’ve “conditioned on” species.</p>
<p>We can take the same data and get a very different story if instead we condition on <code>island</code>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Now, the height of the blue bar in the lower left of the plot shows the proportion of penguins from Biscoe that were Gentoo: 119 / 163 = .730.</p>
<p>One last question before we move on: of these two charts, which one more clearly shows the species distribution on Dream Island? Dream shows up in both charts, but only one gives you a good answer to this question.</p>
<p>The answer to this question comes from the second chart. Here the species breakdown on Dream is clearly shown in the middle bar: a bit more than half are Chinstrap, the rest are Adelie. Trying to pry this information out of the first chart is actually impossible! When we conditioned on species, we lost the relative numbers of Chinstraps and Adelies - where they found in equal numbers or were there 100 Chinstraps for every Adelie? That information can’t be back-engineered from the first chart, and without it, we can’t reconstruct the distribution as seen in the middle bar of the second chart.</p>
<p>The lesson from this is powerful: if you wish to make a claim rooted in a conditional proportion and are using a normalized bar chart, it is essentially to think carefully about <em>which</em> conditional proportion your chart is displaying.</p>
</section><section id="identifying-an-association" class="level3"><h3 class="anchored" data-anchor-id="identifying-an-association">Identifying an association</h3>
<p>Is there an association between species and which island they are found on? With a clearer sense of proportions under our belt, we can define this more precisely.</p>
<dl>
<dt><strong>Association</strong></dt>
<dd>
There is an association between two categorical variables if the conditional proportions vary as you move from one one level of the conditioning variable to the next.
</dd>
</dl>
<p>This is best illustrated by showing the previous plot of the real data right next to an example of what a penguins data set would look like that exhibits <em>no</em> association between <code>species</code> and <code>island</code>.</p>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="notes_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="notes_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>In plot on the right, as you gaze from left to right, looking across first Biscoe, then Dream, then Torgersen Islands, you see that the distribution of species is unchanged. There are always the most Gentoos, then Chintraps, then Adelies, regardless of the island. This indicates that there is no association between the variables in this data set.</p>
<p>This stands in stark contrast to the plot of the real data on the left. On Biscoe Island, Gentoo penguins dominate, with a smaller proportion of Adelies. Chinstraps are nowhere to be found. On Dream Island, its the Gentoos that are absent and we find roughly similar proportions of Chinstraps and Adelies. On Torgersen we observed only Adelies. This data set exhibits a strong association between <code>species</code> and <code>island</code>.</p>
<!-- - start with one variable -->
<!-- - discuss the notion of a "distribution -->
<!-- - do "conditioning" using filtering -->
<!-- ### One variable -->
<!-- - one way table -->
<!-- - counts -->
<!-- - proportion -->
<!-- - barchart -->
<!-- - normalized barchart -->
<!-- ![](images/one-var.jpg){fig-alt="Sketch showing the flow for one variable from raw data to contingency table to barchart." fig-align=center} -->
</section></section><section id="the-ideas-in-code" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="the-ideas-in-code">The Ideas in Code</h2>
<section id="help-and-arguments" class="level3 page-columns page-full"><h3 class="anchored" data-anchor-id="help-and-arguments">Help and Arguments</h3>
<p>Every function in R has a built-in help file that tells you about how it works. It can be accessed using <code>?</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">?</span><span class="va">mean</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This will pop up the help file in a tab next to your Files tab in the lower right hand corner of RStudio. In addition to describing what the function does, the help file lists out the function’s <strong>arguments</strong>. Arguments are the separate pieces of input that you can supply to a function and they can be <em>named</em> or <em>unnamed</em>.</p>
<p>In <em>Taxonomy of Data</em>, we created a vector called <code>my_fav_numbers</code> and then calculated its mean using the <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> function.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">my_fav_numbers</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">9</span>, <span class="fl">11</span>, <span class="fl">19</span>, <span class="fl">28</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">my_fav_numbers</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.75</code></pre>
</div>
</div>
<p>In the second command that we entered above, we used a single <em>unnamed argument</em>, <code>my_fav_numbers</code>. We could have alternatively written this with a <em>named argument</em>:</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">my_fav_numbers</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.75</code></pre>
</div>
</div>
<p>As the help file suggests, <code>x</code> is the R object (here a vector of numbers) that you want to take the mean of. You can always pass objects to a function as named arguments, or if you want to be more concise, you can pass it unnamed and R will rely on the <em>order</em> to figure things out.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div id="fig-mean-help" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center" alt="Screenshot of the helpfile from the mean function.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-mean-help-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mean-help.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Screenshot of the helpfile from the mean function." width="300">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mean-help-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Help file for <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>.
</figcaption></figure>
</div>
</div></div><p>To test how this actually works, let’s add a second unnamed argument to our function. From reading the help file, you learn that you can supply it a <code>trim</code> argument to trim off some percent of the highest and lowest values before computing the mean. The <strong>default value</strong> of this argument is 0, but we can change this. Let’s trim off 25% from the lower end and 25% from the upper end.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">my_fav_numbers</span>, <span class="fl">.25</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15</code></pre>
</div>
</div>
<p>It worked! We trim off the 9 and the 28, then take <span class="math inline">\((11 + 19) / 2 = 15\)</span>. We can also write the command using named arguments. The code will be a bit more verbose but the answer will be the same.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">my_fav_numbers</span>, trim <span class="op">=</span> <span class="fl">.25</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15</code></pre>
</div>
</div>
<p>What happens if we use unnamed arguments but change the order? Let’s find out.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fl">.25</span>, <span class="va">my_fav_numbers</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in mean.default(0.25, my_fav_numbers): 'trim' must be numeric of length one</code></pre>
</div>
</div>
<p>Since there are no names, R looks at the second argument and expects it to be the a proportion between 0 and .5 that it will use to trim. You have passed it a vector of three integers instead, so it’s justified in complaining.</p>
</section><section id="libraries" class="level3"><h3 class="anchored" data-anchor-id="libraries">Libraries</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/tidyverse-hex.png" class="quarto-figure quarto-figure-center figure-img" style="width:50.0%;height:50.0%"></p>
<figcaption>The <code>tidyverse</code> library, which contains many useful packages for data science</figcaption></figure>
</div>
<p>In <em>Taxonomy of Data</em>, we learned about a few different functions that can be used on vectors, such as <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>. We also learned about a function called <code><a href="https://rdrr.io/r/base/data.frame.html">data.frame()</a></code>, which allowed us to bring vectors together as part of a new structure called a data frame, with each of the vectors used as columns.</p>
<p>While the base functionality provided by R is powerful, developers often seek to find more efficient ways to complete tasks. In doing so, they push the power of R forward. R has a vast ecosystem of <strong>libraries</strong> that add new functions. Any installed library can be loaded with the <code><a href="https://rdrr.io/r/base/library.html">library()</a></code> function. Here, we will load the <code>tidyverse</code> library, one of the core external libraries that we will be using this semester.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To use these functions within this library (or any other library), you will need to run the above line of code <em>each time you start an RStudio session!</em></p>
<p>The <code>tidyverse</code> library has many different <strong>packages</strong> which contain smaller pieces of functionality. Today, our focus is to summarize categorical data, and one avenue we have explored already is a visual summary; a bar chart. Let’s explore how the plots shown earlier in this set of notes were made. We will use <code>ggplot2</code>, <code>tidyverse</code>’s resident visualization package.</p>
<p>First, we should load the <code>penguins</code> data into our environment. The <code>penguins</code> data is actually located in a special library made just for this course called <code>stat20data</code>. This library hosts the datasets which will be the subjects of your labs. Therefore, we need to load this library first.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">stat20data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we can load in the <code>penguins</code> data by using the aptly named <code>data</code> function.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">penguins</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once you do this, you will see the <code>penguins</code> dataset, in all of its glory, appear in the environment pane at the top right of your RStudio session (you may need to click in the area once or twice).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/environment.png" class="quarto-figure quarto-figure-center figure-img" style="width:50.0%;height:50.0%"></p>
</figure>
</div>
<p>You can click the blue dropdown arrow to see each variable in the dataset, or for a more traditional view, you can click the white spreadsheet icon to the right:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/viewer.png" class="quarto-figure quarto-figure-center figure-img" style="width:50.0%;height:50.0%"></p>
</figure>
</div>
<p>Now, we’re ready to write some <code>ggplot2</code> code and make our first visualization of the year! We will create the exact stacked, normalized bar chart you saw earlier in the notes.</p>
</section><section id="a-first-visualization-with-ggplot2" class="level3"><h3 class="anchored" data-anchor-id="a-first-visualization-with-ggplot2">A first visualization with <code>ggplot2</code>
</h3>
<p>The main function within the <code>ggplot2</code> package is, well, <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="499"></p>
</figure>
</div>
</div>
</div>
<p>The <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code> function takes as its first argument a data frame (the <code>data</code> argument). By itself, there’s not much to look at; it just creates a blank canvas.</p>
<p>Let’s now indicate how we want to map our <em>variables</em> to each area of the plot. For now, let’s just focus on the species of penguin; we’ll handle the island later.</p>
<p>We had species of penguin on the horizontal (<code>x</code>) axis. This piece of information (which is known as an <strong>aesthetic attribute</strong> of the plot), goes into a second argument called <code>mapping</code> and within a function called <code><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes()</a></code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, </span>
<span>       mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">species</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Now we’re getting somewhere. We can see the x axis has been set up with labels for the species of penguins.</p>
<p>All that is left is to actually put the observations on the plot. We do this by declaring what <strong>geometry</strong> we want and adding this information to our existing code. We can add this information via a new <em>layer</em>, which can be added on by using the <code>+</code> syntax and taking a newline.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, </span>
<span>       mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">species</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>The layer we added was a geometry layer corresponding to the bar chart, called <code><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar()</a></code>. In tomorrow’s notes, you will similarly named geometry layers relating to visualizations for numerical data.</p>
<p>Note that the bars are not colored like before, but are just gray. This is because we are missing the island variable! Island was represented by coloring in (filling) the bars for us according to the <em>conditional proportions</em> of penguins within a specific species belonging to a specific island. We can include this by adding to our <code><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes()</a></code> function in the original layer.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, </span>
<span>       mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">species</span>, </span>
<span>                     fill <span class="op">=</span> <span class="va">island</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Almost there! Note that what we have right now is just a <em>stacked</em> bar chart. There’s one more fix that we need to apply. Note that <code><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar()</a></code> can be thought of as a function as well. One of its arguments, <code>position</code>, will help us solve this issue<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. <code>position</code> defaults to a stacked bar chart, but we can fix this by supplying it with <code>"fill"</code>!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, </span>
<span>       mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">species</span>, </span>
<span>                     fill <span class="op">=</span> <span class="va">island</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"fill"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>A side-by-side (dodged) by chart can be produced by replacing <code>"fill"</code> with <code>"dodge"</code>. To recover the original, stacked bar chart, use <code>"stack"</code>!</p>
<p>There we have it! Looking forward:</p>
<ol type="1">
<li>In our very next lecture, you’ll learn how to use <code>ggplot2</code> to make visualizations of numerical variables.</li>
<li>We will also learn more about the machinery behind <code>ggplot2</code> through a dedicated lecture in a couple of weeks.</li>
</ol></section></section><section id="summary" class="level2"><h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>A wise statistician once said, “In statistics, most of what we do is add things up. Sometimes we divide. The challenging part is deciding <em>what</em> to add and divide.” This captures the deceptive simplicity of summarizing categorical data. Categorical summaries involve counts of categories or proportions. Those proportions can be joint proportions, marginal proportions, or conditional proportions. Those counts and proportions are commonly displayed in contingency tables or in bar charts. Subtle choices of which proportion to present results in the telling of dramatically different stories.</p>


</section><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1"><p>Smialek, Jeanna (2022, May 11). Consumer Prices are Still Climbing Rapidly. <em>The New York Times</em>. <a href="https://www.nytimes.com/2022/05/11/business/economy/april-2022-cpi.html" class="uri">https://www.nytimes.com/2022/05/11/business/economy/april-2022-cpi.html</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>To learn more, check out the Wikipedia page on the <a href="https://en.wikipedia.org/wiki/United_States_Consumer_Price_Index">CPI in the US</a> and the exhaustive description of how the data is collected at the <a href="https://www.bls.gov/cpi/overview.htm#:~:text=The%20CPI%20represents%20changes%20in,life%20insurance">US Bureau of Labor Statistics</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>This argument is generally not important for the other plots we create in this course, which is why in the initial piece of code featuring <code><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar()</a></code>, it was not specified at all.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../1-questions-and-data/02-taxonomy-of-data/notes.html" class="pagination-link  aria-label=" the="" taxonomy="" of="" data="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">The Taxonomy of Data</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../2-summarizing-data/02-summarizing-numerical-data/notes.html" class="pagination-link" aria-label="Summarizing Numerical Data">
        <span class="nav-page-text">Summarizing Numerical Data</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
<li class="nav-item">
    <a class="nav-link" href="https://www.netlify.com/">
<p>This site is hosted by Netlify.</p>
</a>
  </li>  
</ul>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
<li class="nav-item">
    <a class="nav-link" href="../../license.html">
<p>License</p>
</a>
  </li>  
</ul>
</div>
  </div>
</footer>


</body></html>